version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Asia/Tokyo'
  - package-ecosystem: 'elm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Asia/Tokyo'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
