version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'elm'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      # https://github.com/hmsk/vite-plugin-elm/issues/386#issuecomment-1356815310
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
