version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    ignore:
      - dependency-name: 'crate-ci/typos'
    groups:
      determinatesystems-actions:
        patterns:
          - 'DeterminateSystems*'
  - package-ecosystem: 'elm'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      stylelint-dependencies:
        patterns:
          - '*stylelint*'
      tsconfig-dependencies:
        patterns:
          - '@tsconfig/*'
