extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es2022: true
parserOptions:
  project: true
rules:
  no-mixed-operators: error
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/prefer-readonly-parameter-types':
    - error
    - ignoreInferredTypes: true
  no-restricted-syntax:
    - error
    - selector: TSEnumDeclaration
      message: >-
        Don't declare enums. ref: https://www.kabuku.co.jp/developers/good-bye-typescript-enum
  # See https://zenn.dev/teppeis/articles/2023-04-typescript-5_0-verbatim-module-syntax for enabling reason
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-import-type-side-effects': 'error'
overrides:
  - files:
      - src/**/*d.ts
  - files:
      - src/**/*d.ts
    rules:
      '@typescript-eslint/no-unused-vars':
        - off
      '@typescript-eslint/prefer-readonly-parameter-types':
        - off
