name: CI - Elm
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-elm.yml'
      - '.node-version'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
  pull_request:
    paths:
      - '.github/workflows/ci-elm.yml'
      - '.node-version'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Add local elm compiler to the PATH
        run: echo './node_modules/elm/bin/' >> $GITHUB_PATH
      - name: Test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Add local elm compiler to the PATH
        run: echo './node_modules/elm/bin/' >> $GITHUB_PATH
      - name: Format Check
        run: npx elm-format --validate src
      - name: Lint
        run: npx elm-review
