name: CI - Elm
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-elm.yml'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
  pull_request:
    paths:
      - '.github/workflows/ci-elm.yml'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Load elm # Workaround to avoid `node_modules/elm/bin/elm: Text file busy`
        run: npx elm --version || true
      - name: Test
        run: npm run test
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Load elm # Workaround to avoid `node_modules/elm/bin/elm: Text file busy`
        run: npx elm --version || true
      - name: Format Check
        run: npx elm-format --validate src
      - name: Lint
        run: npx elm-review
