name: CI - Elm
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-elm.yml'
      - '.tool-versions'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
  pull_request:
    paths:
      - '.github/workflows/ci-elm.yml'
      - '.tool-versions'
      - 'elm.json'
      - 'elm-tooling.json'
      - 'package.json'
      - 'package-lock.json'
      - '**/*.elm'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  test:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Test
        run: npm run test
  lint:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Format Check
        run: npx elm-format --validate src
      - name: Lint
        run: npx elm-review
