name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.github/workflows/dependency-review.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.github/workflows/dependency-review.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'LICENSE'
      - '.editorconfig'
      - 'dprint.json'
      - 'README.md'
      - '.vscode/**'
jobs:
  asdf-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: kachick/action-parse-asdf-tool-versions@v1
        id: parse
    outputs:
      tool-versions: '${{ steps.parse.outputs.json }}'
  check:
    needs: [asdf-parser]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).nodejs }}'
          cache: npm
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: '${{ fromJson(needs.asdf-parser.outputs.tool-versions).elm }}'
      - name: Test & Lint
        run: npm run check
