name: 💂➕
on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'elm.json'
      - 'elm-tooling.json' # I don' have confident this is needless or not
      - 'package.json'
      - 'package-lock.json'
      - '*.nix'
      - 'flake.lock'

permissions:
  contents: read

jobs:
  dependency-review:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
