name: Deploy products
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'tests/**'
      - '.github/workflows/test.yml'
  pull_request:
    paths-ignore:
      - 'tests/**'
      - '.github/workflows/test.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: install npm dependencies
        run: npm install
      - name: Get Pull Request Number
        id: pr
        run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          staging_prefix=pr-${PR_NUMBER}
          cp -rf statics "docs/$staging_prefix"
          elm make src/Main.elm --output="docs/$staging_prefix/main.js"
        if: github.event_name == 'pull_request'
        env:
          PR_NUMBER: ${{ github.event.number }}
      - run: |
          cp -rf statics "docs/latest"
          elm make src/Main.elm --output=docs/latest/main.js
        if: github.event_name != 'pull_request'
      - name: git setting
        run: |
          git config --local user.email "kachick1+mobu-elm@gmail.com"
          git config --local user.name "mobu-elm bot"
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d-%H%M-UTC"`
          BRANCH_NAME="deploy-$DATE"
          git checkout -b "$BRANCH_NAME"
          git add docs package-lock.json
          git commit -m 'Update with latest code'
          git push origin "$BRANCH_NAME":gh-pages --force
