name: Send Elm dependencies
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/elm-dependency-submission.yml'
      - 'elm.json'
      - 'elm-tooling.json'

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

jobs:
  elm-dependency-submission:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Run snapshot action
        uses: kachick/elm-dependency-submission@v3
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
