name: Linters
on:
  push:
    branches: [main]
  pull_request:

jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
        with:
          # Keep same version as used in *.nix
          dprint-version: '0.40.2'

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Keep same version as used in *.nix
      - uses: crate-ci/typos@v1.16.8
        with:
          # https://github.com/crate-ci/typos/issues/779#issuecomment-1635741586
          files: |
            .
            .github
            .vscode
