name: Test & Lint
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - '.prettierrc'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - '.prettierrc'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: install npm dependencies
        run: npm install
      - name: Test
        run: npx elm-test
      - name: Lint Elm code
        run: npx elm-review
      - name: Lint JavaScript/TypeScript code
        run: npm run prettier-check && npm run eslint
