name: Test & Lint
on:
  push:
    branches: [main]
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.github/workflows/dependency-review.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/dependabot.yml'
      - '.github/workflows/merge-bot-pr.yml'
      - '.github/workflows/firebase-hosting-merge.yml'
      - '.github/workflows/firebase-hosting-pull-request.yml'
      - '.github/workflows/dependency-review.yml'
      - 'firebase.json'
      - '.firebaserc'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - 'dprint.json'
      - '.eslintrc.js'
      - 'README.md'
      - '.vscode/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.npm-cache.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Lint Elm code
        run: npx elm-review
      - name: Lint JavaScript/TypeScript code
        run: npm run eslint
