name: Test
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github\workflows\.github\dependabot.yml'
      - '.github\workflows\deploy_products.yml'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github\workflows\.github\dependabot.yml'
      - '.github\workflows\deploy_products.yml'
      - 'MIT-LICENSE.txt'
      - '.editorconfig'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: install npm dependencies
        run: npm install
      - name: Test
        run: ./node_modules/elm-test/bin/elm-test
